version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: Dasp-143
      MYSQL_DATABASE: teamcobra
      MYSQL_USER: cobradb
      MYSQL_PASSWORD: Dasp-143
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_backend
    depends_on:
      - db
    ports:
      - "4000:4000"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USERNAME: cobradb
      DATABASE_PASSWORD: Dasp-143
      DATABASE_NAME: teamcobra

volumes:
  mysql_data:
