version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_USER: cobradb
      MYSQL_PASSWORD: 8431676017@Db
      MYSQL_ROOT_PASSWORD: 8431676017@Db
      MYSQL_DATABASE: cobradb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_backend
    depends_on:
      - db
    ports:
      - "4000:4000"
    environment:
      DATABASE_HOST: cobra-database.mysql.database.azure.com
      DATABASE_PORT: 3306
      DATABASE_USERNAME: cobradb
      DATABASE_PASSWORD: {your-password}
      DATABASE_NAME: TeamCobra

volumes:
  mysql_data:
